theme = "dong"
baseURL = '/'
languageCode = 'en-us'

# Params
[Params]
navBrand = 'WebDong.dev'
navBrandShort = 'WebDong'

brand = 'WebDong'
brandtc = 'WebDong.dev'
brandLogo = 'â—¢â—¢â—¢'
brandUrl = 'https://www.webdong.dev/'
brandUrlShort = 'https://www.instagram.com/webdong.dev'
brandEmail = 'webdongdev@gmail.com'
brandPhone = '09-3636-1996'
# brandLocation = 'No. 129, Section 3, Sanmin Rd, North District, Taichung City, 404'
# brandLocationtc = 'è‡ºä¸­å¸‚åŒ—å€ä¸‰æ°‘è·¯ä¸‰æ®µ129è™Ÿ'
brandWorktime = 'ç‡Ÿæ¥­æ™‚é–“ 9:30am - 18:30pm'
brandFavicon = "D"
brandFaviconSize = "60"

googleAnalytics = 'G-S6W57VD15P'

brandYoutube = '#'
brandInstagram = 'https://www.instagram.com/webdong.dev'
brandBehance = ''

slogan = "å°ˆæ¥­çš„è§’åº¦æœ‰è¶£åœ°ç©ç¶²é "
brandDescription = "ç¶²é æ±æ± Webdong.dev  æ˜¯ä¸€å€‹å°ˆæ³¨æ–¼å”åŠ©ä½ é–‹ç™¼ç¶²é çš„åŠ©æ‰‹ã€‚ "

utteranceRepo = "riceball-tw/web-dong-dong"
utteranceIssueTerm = "pathname"
utteranceLabel = "ğŸ’¬"
utteranceTheme = "github-light"

# Pagination
paginate = 10
PaginatePath = ""

# Cloudinary
cloudinaryImg = "https://res.cloudinary.com/webdong/image/upload"

# Navbar
[menu]
[[menu.main]]
  # Identifier must match the section name
  identifier = 'home'
  name = 'é¦–é '
  title = 'ä¸‰è§’æ±æ±é¦–é '
  url = '/'
  weight = 1
[[menu.main]]
  identifier = 'about'
  name = 'é—œæ–¼'
  title = 'é—œæ–¼ä¸‰è§’æ±æ±'
  url = '/about/'
  weight = 2
[[menu.main]]
  identifier = 'post'
  name = 'æ–‡ç« '
  title = 'æŸ¥çœ‹éƒ¨è½æ ¼æ–‡ç« '
  url = '/post/'
  weight = 3
[[menu.main]]
  identifier = 'project'
  name = 'å°ˆæ¡ˆ'
  title = 'æŸ¥çœ‹å°ˆæ¡ˆä½œå“'
  url = '/Project/'
  weight = 4

# Sitemap
[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

# Taxonomy
[taxonomies]
  category = "category"
  tag = "tag"
  project = "project"

# Markup Engine
enableEmoji = true
[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'dracula'
    tabWidth = 4

  [markup.tableOfContents]
    endLevel = 4
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[server]
[[server.headers]]
  for = '/*'
  [server.headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Content-Security-Policy = "'default-src' 'self' data: 'unsafe-eval' 'unsafe-inline' www.google-analytics.com www.googletagmanager.com https://i.imgur.com https://res.cloudinary.com www.youtube-nocookie.com www.youtube.com "